[package]
name = "nebula-store"
version = "0.6.1"
edition = "2024"

[dependencies]
gtk4 = "0.8"
libadwaita = "0.6"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
glib-build-tools = "0.17"
